#!/usr/bin/env python3
"""
Convert FX3 firmware file to compressed C header.

Compression format (optimized for firmware with large zero regions):
  0x00         -> Escape byte, followed by:
    0x00, LO, HI    -> Zero run of (LO | HI<<8) bytes (1-65535)
    0x01, byte      -> Literal byte (for escaping non-zero after 0x00)
    0x02, count, byte -> Run of 'count' identical non-zero bytes (3-255)
  Other bytes  -> Literal

This achieves good compression on firmware with large zero-padded regions
while keeping decompression simple and fast.
"""

import sys
import os

def compress(data):
    """Compress data with zero-run optimization."""
    result = []
    i = 0
    n = len(data)

    while i < n:
        byte = data[i]

        # Count consecutive identical bytes
        count = 1
        while i + count < n and data[i + count] == byte and count < 65535:
            count += 1

        if byte == 0x00 and count >= 2:
            # Zero run: 0x00, 0x00, LO, HI
            result.extend([0x00, 0x00, count & 0xFF, (count >> 8) & 0xFF])
            i += count
        elif byte != 0x00 and count >= 4:
            # Non-zero run (need 4+ to be worth it): 0x00, 0x02, count, byte
            actual_count = min(count, 255)
            result.extend([0x00, 0x02, actual_count, byte])
            i += actual_count
        elif byte == 0x00:
            # Single zero: escape it
            result.extend([0x00, 0x01, 0x00])
            i += 1
        else:
            # Literal non-zero byte
            result.append(byte)
            i += 1

    return bytes(result)

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <firmware.fw> [output.h]")
        sys.exit(1)

    fw_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else "fx3_firmware_data.h"

    with open(fw_path, "rb") as f:
        raw_data = f.read()

    compressed = compress(raw_data)

    ratio = len(compressed) / len(raw_data) * 100
    print(f"Original size:   {len(raw_data):,} bytes")
    print(f"Compressed size: {len(compressed):,} bytes ({ratio:.1f}%)")

    # Generate C header
    with open(out_path, "w") as f:
        f.write("/*\n")
        f.write(" * Embedded FX3 firmware (RLE compressed)\n")
        f.write(f" * Original size: {len(raw_data)} bytes\n")
        f.write(f" * Compressed size: {len(compressed)} bytes\n")
        f.write(" * Generated by fw2header.py\n")
        f.write(" */\n\n")
        f.write("#ifndef FX3_FIRMWARE_DATA_H\n")
        f.write("#define FX3_FIRMWARE_DATA_H\n\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <stddef.h>\n\n")
        f.write(f"#define FX3_FIRMWARE_ORIGINAL_SIZE {len(raw_data)}\n")
        f.write(f"#define FX3_FIRMWARE_COMPRESSED_SIZE {len(compressed)}\n\n")
        f.write("static const uint8_t fx3_firmware_compressed[] = {\n")

        # Write data in rows of 16 bytes
        for i in range(0, len(compressed), 16):
            chunk = compressed[i:i+16]
            hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {hex_vals},\n")

        f.write("};\n\n")
        f.write("#endif /* FX3_FIRMWARE_DATA_H */\n")

    print(f"Written to: {out_path}")

if __name__ == "__main__":
    main()
